### PR TITLE
Fix multiple paths by dedup

### LINKED ISSUE #57: Fix a bug with duplicate paths
We can pass an argument to `dotenv-linter` to include some files to check:

```bash
$ dotenv-linter -i .my-env-file
.env:1 Leading space detected
.my-env-file:1 Leading space detected
```

If the file already exists in the paths, we will get a duplicate result:

```bash
$ dotenv-linter -i .env -i .env
.env:1 Leading space detected
.env:1 Leading space detected
.env:1 Leading space detected
```

Need to fix that and write tests for that case.

Link: https://github.com/mgrachev/dotenv-linter/blob/master/src/lib.rs#L101

### PR DESCRIPTION
**Pull request by mstruebing**
closes #57

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -22,7 +22,8 @@ pub struct LineEntry {
 }
 
 pub fn run(matches: clap::ArgMatches) -> Result<(), Error> {
-    let paths = dotenv_files(matches)?;
+    let mut paths = dotenv_files(matches)?;
+    paths.dedup();
```
Comment (mgrachev) [inline src/lib.rs]: It doesn't work for the case:
```bash
$ dotenv-linter -i .my-env-file -i .env
.env:1 Leading space detected
.my-env-file:1 The line has spaces around equal sign
.env:1 Leading space detected
```

Comment (mgrachev) [reply src/lib.rs]: I think you should use [HashSet](https://doc.rust-lang.org/std/collections/struct.HashSet.html) to fix that.

**Comment by mgrachev** [comment]
@mstruebing 👋Thank you for your contribution! 🚀

I've left a few comments. Could you please fix them and write integration tests to check that this functionality works properly?

File: src/lib.rs (hunk 1 above)
Comment (mstruebing) [reply src/lib.rs]: Ah yes, because `dedup` only removes duplicates which follow after each other. Will fix :)

Comment (mstruebing) [reply src/lib.rs]: A sort before the `dedup` would also work. But I think the HashSet is better.

File: .github/workflows/ci.yml [hunk 2]
```diff
@@ -82,3 +82,26 @@ jobs:
     - uses: actions-rs/cargo@v1
       with:
         command: build
+
+  integration:
```
Comment (mgrachev) [inline .github/workflows/ci.yml]: I mean you should write integration tests like that - https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html

For example: Create the directory `tests` and test the function `run` from `lib.rs`.

Comment (mgrachev) [reply .github/workflows/ci.yml]: @mstruebing I've thought, probably I should write integration tests instead of you because I have some ideas. Don't you mind?

Comment (mstruebing) [reply .github/workflows/ci.yml]: Yes sure, sorry for not pushing this forward :)

**Comment by mgrachev** [comment]
@mstruebing Thank you! ❤️

File: src/lib.rs (hunk 1 above)
Comment (mgrachev) [reply src/lib.rs]: @mstruebing `sort` and `dedup` is better 😃
https://github.com/mgrachev/dotenv-linter/pull/68
